digital-preservation/droid

droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/archive/ArcArchiveContentIdentifier.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/archive/ArchiveContentIdentifier.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/archive/GZipArchiveContentIdentifier.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/archive/TarArchiveContentIdentifier.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/archive/WarcArchiveContentIdentifier.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/archive/ZipArchiveContentIdentifier.java
droid-core-interfaces/pom.xml
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/archive/ArcArchiveHandler.java
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/config/DroidGlobalProperty.java
droid-results/src/main/resources/META-INF/spring-results.xml

java.net rules for URI parsing enforce restricted characters on querystrings, causing droid to exit in the middle of an ARC file when it met any.

Relaxed rules on allowable urls in Arc files

---

droid-parent/pom.xml

Version 3.2.1 has a CVSS 10.0 vulnerability. That's the worst kind of
vulnerability that exists. By merely existing on the classpath, this
library causes the Java serialization parser for the entire JVM process
to go from being a state machine to a turing machine. A turing machine
with an exec() function!
https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-8103
https://commons.apache.org/proper/commons-collections/security-reports.html
http://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/

Upgrade Apache Commons Collections to v3.2.2

---

droid-binary/bin/droid.bat
droid-binary/bin/droid.sh

This change updates the Windows and Unix scripts to allow them to be invoked from outside their installation directory or through symbolic links, and guards against paths which include spaces.
Tested on MacOS 10.12, MinGW64, and Windows 10.

Support invoking DROID outside its home directory

---

.travis.yml

Trusty(14.04) don't support oracle java7.
https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming

Build on precise (ubuntu 12.04)

---

README.md
appveyor.yml
droid-build-tools/src/main/resources/checkstyle-main.xml
droid-parent/pom.xml

I am hoping that by adding support for the AppVeyor CI (which runs on Microsoft Windows), this will help us ensure that DROID continues to work on both Linux and Windows in future.

Adds support for Appveyor CI which runs on Windows

---

.travis.yml
droid-parent/pom.xml
droid-results/pom.xml
droid-results/src/test/java/uk/gov/nationalarchives/droid/planet/xml/dao/JpaPlanetsXMLDaoTest.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/profile/JpaProfileDaoTest.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/profile/JpaProfileFilterTest.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/profile/ProfileResourceNodePersistenceTest.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/report/dao/JpaReportDaoTest.java

This PR moves DROID to require Java 8 as a minimum. It also updates DROID to Spring 5; which is a pre-requisite to enabling support for Java 9 platforms.

Move droid to Java 8

---

.travis.yml
droid-binary/bin/droid.bat
droid-binary/bin/droid.sh
droid-parent/pom.xml
droid-results/pom.xml
droid-results/src/main/java/uk/gov/nationalarchives/droid/signature/PronomSignatureService.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/planet/xml/dao/JpaPlanetsXMLDaoTest.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/profile/JpaProfileDaoTest.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/profile/JpaProfileFilterTest.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/profile/ProfileResourceNodePersistenceTest.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/report/dao/JpaReportDaoTest.java
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/filechooser/ResourceSelectorDialog.java
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/treemodel/ExpandingTreeListener.java
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/worker/DroidJob.java

Closes https://github.com/digital-preservation/droid/issues/186
This PR builds atop PRs:
1. https://github.com/digital-preservation/droid/pull/187
and adds support for running DROID on Java 9 JVM's, whilst still only requiring Java 8 as a minimum.
Best bet would be to merge https://github.com/digital-preservation/droid/pull/187 first.

Add support for Java 9

---

droid-parent/pom.xml
droid-results/pom.xml
droid-results/src/test/java/uk/gov/nationalarchives/droid/report/dao/JpaReportDaoTest.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/signature/PronomSignatureServiceTest.java
droid-results/src/test/resources/jpa-test.properties

Remove direct derby-db data files modification. Instead copy database files to target directory and run all queries on data files in target directory.

Cleanup build.

---

droid-results/src/test/java/uk/gov/nationalarchives/droid/util/FileUtilTest.java

FileUtilTest tests the output of FileUtil.formatFileSize() (which
depends on the locale of the machine the test is run on) against a
literal string (which does not depend on the locale).
This will fail on non-english locales. This fix uses the decimal
separator and grouping separator of the machine running the test and
should make the test independent of the locale it is executed on.
This PR is the exact solution already pointed out in the comments of
#197 
Fixes #197 and #198.

Fixes broken test when built on non-english locale

---

droid-swing-ui/src/test/java/uk/gov/nationalarchives/droid/gui/filechooser/ResourceFileChooserTest.java

- replace "All Files" by the description of the default AcceptAllFileFilter (for example in French it's "Tous les fichiers")

Fix: test not convenient when building in non english environment

---

.travis.yml
appveyor.yml
droid-core-interfaces/pom.xml
droid-parent/pom.xml
droid-results/pom.xml
droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/FilterPredicate.java
droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/ProfileContextLocator.java
droid-swing-ui/pom.xml
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/config/ConfigDialog.java

- fixed dependency org-openide-util that prevented to use openJdk11 and used official repository rather than outdated TNA third party repository
- set default java version from 1.8 to 11 (most of the work had been done by Radek)
- did a series of non-breaking updates (or requiring small changes) on dependencies, using github dependabot and maven dependency tool
Update 10/10:
won't change default version to Java 11, still keep compatible with jdk 8 to 11 and updated dependencies

shifting support forward to Java 11 and fix/update dependencies

---

droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/export/JDBCSqlItemReader.java

fix Null Pointer exception when exporting profile with extension mismatch filters turned on 
https://github.com/digital-preservation/droid/issues/231

fix: NPE on export when extension mismatch filters turned on 

---

droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/DroidMainFrame.form
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/DroidMainFrame.java
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/ProfileForm.form
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/ProfileForm.java

changed two components in UI to remove visual issues: second menu row with icons which was cropped + bottom right throttle button which was showing an extra label on top of the throttle.
(code generated with netbeans GUI designer, and refined afterwards manually)
from
to
compared to previous version run with Java 8

Fix display jdk 11

---

droid-results/src/main/java/uk/gov/nationalarchives/droid/submitter/SubmissionGateway.java

This small change gets rid of the contant exception stack trace in normal DROID operation processing awkward zip files, unless  you're in debug log mode - where you get the stack trace.
This makes looking at DROID output much easier in normal operation.   Mostly it's things like zip files which the library can't interpret, not errors in the software. Things that aren't actually errors shouldn't dump stack traces onto the warn log mode.

Only output exception stack traces when in debug mode.

---

droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/FilterCriterionImpl.java

* Instead of returning the enum object itself, we must return it's
ordinal value, as the database has an integer field.

FIX: exception on setting enum based filter.

---

droid-swing-ui/pom.xml

to ensure good maintenance and prevent upgrading library while not taking into account overridden class

add: comment in pom about hotfix on org-netbeans-swing-outline

---

droid-container/src/main/java/uk/gov/nationalarchives/droid/container/AbstractContainerIdentifier.java
droid-container/src/main/java/uk/gov/nationalarchives/droid/container/ContainerSignatureFileReader.java
droid-container/src/test/java/uk/gov/nationalarchives/droid/container/odf/OdfIdentifierTest.java
droid-container/src/test/java/uk/gov/nationalarchives/droid/container/ole2/Ole2RootFileTest.java
droid-container/src/test/java/uk/gov/nationalarchives/droid/container/ooxml/OoXmlIdentifierTest.java
droid-results/src/main/resources/META-INF/spring-results.xml

At present the container signature file is parsed twice: once when the ZipIdentifier is instantiated, and again when the OLE2Identifier is.
This PR creates a new bean that caches the container signature definitions, and modifies the container identifiers to use the bean instead of parsing the file themselves.

Only parse container sigs once

---

droid-core-interfaces/pom.xml
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/control/PauseAspect.java
droid-parent/pom.xml
droid-results/pom.xml
droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/ProfileInstanceManagerImpl.java
droid-results/src/main/java/uk/gov/nationalarchives/droid/submitter/SubmissionGateway.java
droid-results/src/main/resources/META-INF/spring-jpa.xml
droid-results/src/main/resources/META-INF/spring-profile.xml
droid-results/src/main/resources/META-INF/spring-results.xml
droid-results/src/main/resources/META-INF/spring-signature.xml
droid-results/src/test/java/uk/gov/nationalarchives/droid/planet/xml/dao/JpaPlanetsXMLDaoTest.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/profile/JpaProfileDaoTest.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/profile/JpaProfileFilterTest.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/profile/ProfileResourceNodePersistenceTest.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/report/dao/JpaReportDaoTest.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/submitter/SubmissionGatewayTest.java
droid-results/src/test/resources/META-INF/spring-test.xml

There's a couple of unnecessary dependencies in DROID.
1.  spring transaction isn't actually used in DROID any more.
2.  aspect oriented programming (AOP) was being used to inject code into a single method.
This PR removes the references to unused dependencies, and gets rid of the completely unnecessary use of AOP, and instead just injects the required class in the single place it's needed using normal Spring.

Shrink dependencies

---

droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/datasource/DerbyPooledDataSourceFactory.java

Ensures the factory only creates a single pool per application context.

Ensure only a single object is created.

---

droid-command-line/pom.xml
droid-command-line/src/main/resources/META-INF/cxf/org.apache.cxf.Logger
droid-command-line/src/main/resources/log4j2.properties
droid-command-line/src/test/resources/log4j2.properties
droid-container/pom.xml
droid-container/src/test/resources/log4j2.properties
droid-core-interfaces/pom.xml
droid-core-interfaces/src/test/resources/log4j2.properties
droid-core/pom.xml
droid-export/pom.xml
droid-export/src/test/resources/log4j2.properties
droid-parent/pom.xml
droid-report/pom.xml
droid-report/src/test/resources/log4j2.properties
droid-results/pom.xml
droid-results/src/test/resources/log4j2.properties
droid-swing-ui/pom.xml
droid-swing-ui/src/main/resources/META-INF/cxf/org.apache.cxf.Logger
droid-swing-ui/src/main/resources/log4j2.properties
droid-swing-ui/src/test/resources/log4j2.properties
droid-tools/pom.xml

The logging is broken and shows this kind of logs when starting the app or running some unit tests.
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
Another type of log was mentioned at startup stating "Starting service Pronom[...]"
Introduced in PR https://github.com/digital-preservation/droid/pull/352 on commit ccd5a6c534a06d76e49250940673a4b13240176b while fixing dependency check issues.
- put back log4j slf4j binding dependency in all modules ran or having unit tests
- tell apache.cxf to use slf4j instead of log4j (was using log4j1 and ignoring log4j2 config)
- set root logger to warn (since it's overridden on tna logs …

fix logging

---

droid-results/pom.xml
droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/export/JDBCSqlItemReader.java

from @dclipsham: one thing i picked up on with the build @Jeremie gave to me - when exporting the CSV, the format identifier columns were not correct - no PUID, name or version listed. I gotta leave now but can replicate tomorrow if needed
https://github.com/digital-preservation/droid/issues/360
introduced on https://github.com/digital-preservation/droid/pull/212 745cc37d0bfcaf5f0f3229bf5a6c2b8e34bb59fa
put back previous code where we retrieve name and version from jdbc query (rather than constant)
- run analysis of a folder on GUI
- make an export
- check that version and name columns are now provided in the export

fix: format version and name was not given anymore in exports

---

droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/NoProfileRunCommand.java
droid-results/src/main/java/uk/gov/nationalarchives/droid/util/FileUtil.java

Tried using the -R flag to recurse folders ./droid.sh -Nr "/home/saurabh/test-data/warc" -Ns "DROID_SignatureFile_V96.xml" -Wt WARC -R
---- It did not recurse the folders underneath which also had WARC files
fix https://github.com/digital-preservation/droid/issues/363
bug introduced in droid/droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/NoProfileRunCommand.java on commit 0d3cbe2 from #167
- run CLI on folder containing sub folders
with following arguments (adapt to your workspace)
```
-R
-Nr
/boot/grub
-Ns
/home/jeremie/.droid6/signature_files/DROID_SignatureFile_V91.xml
-Nc
/home/jeremie/.droid6/container_sigs/container-signature-20170330.xml
```
- verify CLI processed sub folders

fix: CLI can browse again folders recursively

---

droid-binary/conf/log4j2.properties
droid-swing-ui/src/main/resources/log4j2.properties

* removes noise from the main DROID log in normal operation.
Note: you won't see these changes unless you get rid of your .droid6 folder.  If you have an existing installation, DROID will continue to use the previous log4j2.properties file already installed.

Only log hikari errors.

---

droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/archive/ArchiveContentIdentifier.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/archive/Bzip2ArchiveContentIdentifier.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/archive/IsoArchiveContainerIdentifier.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/archive/RarArchiveContainerIdentifier.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/archive/SevenZipArchiveContainerIdentifier.java
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/archive/ArcArchiveHandler.java
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/resource/BZipIdentificationRequest.java
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/resource/GZipIdentificationRequest.java

since latest work on CLI and GUI on managing archives and web archives, we couldn't run the CLI or GUI on the skeleton suite without disabling expansion of sub-archives.
multiple failures on skeleton suite files (which are valid regarding signatures, but not actually valid files that you can open, so we can consider them as corrupted), due to multiple reasons:
- the difference in the management of different formats (some raise exceptions, some just log the error)
- null pointer exception when trying to close the reader on non-existing subfiles
fix https://github.com/digital-preservation/droid/issues/371
fix another bug previously identified: bug: CLI on skeleton suite throws NPE on Bzip2 embedded archive
depends on https://github.com/digital-preservation/droid/pull/376 because it makes …

Fix skeleton issue 

---

droid-parent/pom.xml

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …

[SECURITY] Use HTTPS to resolve dependencies in Maven Build

---

droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/DroidCommandLine.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/CommandLineParam.java

fix https://github.com/digital-preservation/droid/issues/387
according to the documentation, when set, the quiet parameter should override the consoleLogThreshold JVM parameter, and define the TNA logger to ERROR. 
It was not taken into account because the processing of the JVM params happen after the spring context (including log4j) was initialized.
manual process at the very start of the CLI app: check for --quiet or -q parameter in app arguments, and set the env variable accordingly
run the CLI in quiet mode, only csv results and errors should appear
```
-R -Nr /boot/grub -Ns /home/jeremie/.droid6/signature_files/DROID_SignatureFile_V96.xml -Nc /home/jeremie/.droid6/container_sigs/container-signature-20200121.xml --quiet
```

fix: processing of the quiet parameter on CLI

---

droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/DroidMainFrame.java
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/export/ExportDialog.form
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/export/ExportDialog.java
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/export/ExportProgressDialog.java

fix: a couple of issues on export dialog: 
- was impossible to close it cancel
- sometimes progress bar would get stuck on screen on small exports while it should be closed automatically
- Cancel button was trimmed vertically
fix https://github.com/digital-preservation/droid/issues/386
run multiple exports with utf8 and utf8 with bom, check that it works without throwing exception nor showing a progress screen that cannot be closed.

fix export dialog

---

droid-binary/bin/droid.bat
droid-binary/pom.xml
droid-binary/src/assembly/filter-windows-with-jre.properties
droid-binary/src/assembly/filter.properties

was using jre file path in both binaries with and without jre. 
Parameterized it
- `mvn package` the droid project
- unzip the 2 binaries in droid/droid-binary/target in separate folders
- run for each the bat file and verify we can run Droid without error.

fix .bat file in bundle without jre

---

droid-binary/bin/droid.bat

Issue in bat script preventing the .bat file from running on Windows from network drive
fix https://github.com/digital-preservation/droid/issues/411
run both bundle with jre and without jre from network drive on Windows
Ensure no exception is thrown (we just couldn't start the application before in the bundle case)
This should just NOT be done, @Dclipsham how can we invite strongly users to avoid running the jre from a network folder? 
As discussed on slack running the local jre to open a jar on the network is one thing (bad idea in my humble opinion as far as performances are concerned), but running the jre and the jar file both on the network is even worse!
I expect complaints in the future about the poor performances of Droid related to that usecase

fix: .bat script in jre bundle to enable running from network drive

---

droid-container/src/main/java/uk/gov/nationalarchives/droid/container/ContainerSignature.java
droid-container/src/main/java/uk/gov/nationalarchives/droid/container/ContainerSignatureMatch.java
droid-container/src/test/java/uk/gov/nationalarchives/droid/container/ContainerSignatureMatchTest.java
droid-container/src/test/java/uk/gov/nationalarchives/droid/container/ContainerSignatureSaxParserTest.java

It looks like we were generating various maps in the codebase for identifying signature entries and comparisons, however when we created the keys in map, we were stripping the trailing slash. When truezip reads a file, the zip entries for siard contains the trailing slash, so our matching mechanism fails. 
Going through the signature files, siard 2.1 is the only path that had a trailing slash so the change won't affect other files. 
[Update Jeremie] fix https://github.com/digital-preservation/droid/issues/418

Fix support for siard 2.1 issue418

---

droid-command-line/pom.xml
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/NoProfileRunCommand.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/filter/Creator/DirectoryStreamFilterCreator.java
droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/filter/Creator/DirectoryStreamFilterCreatorTest.java

Fix for #425 
Moved the DirectoryStream filter creation out of the command line class and implemented the differences based on whether we are recursing or not. Added unit tests to cover existing as well as amended scenario 
Setup:
Create a folder structure and setup a few files as follows (easy to get a variety on image files)
```
*    test-files
*       |
*       + flying.gif
*       |
*       + india-na.jpeg
*       |
*       + rocket.gif
*       |
*       + the_national_archives_icon.png
*       |
*       + tna.jpeg
*       |
*       +--------- one-more
*                     |
*                     + flying.gif
*                     |
*                     + the_national_archives_icon.png
*                     |
*                     + tna.jpeg
```
1. Run droid CLI with following …

Filter by extension should work when recursing folders

---

droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/DroidMainFrame.form
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/DroidMainFrame.java
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/config/ConfigDialog.form
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/config/ConfigDialog.java
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/filter/FilterDialog.form
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/filter/FilterDialog.java
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/report/ReportDialog.form
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/report/ReportDialog.java

fix https://github.com/digital-preservation/droid/issues/427
Check every single point above on Windows 10

Fix graphical glitches on Windows 10

---

droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/archive/IsoArchiveContainerIdentifier.java

fix https://github.com/digital-preservation/droid/issues/433
prefix in CLI was wrong when expanding ISO archives, showing "zip" instead of "iso"
- Run in CLI the following on a folder including ISO and TAR archives (or any other than TAR - change CLI accordingly)
- check output, make sure error from Paul is corrected (and we see iso at the beginning of lines mentioning the analysis of first children in ISO archives)
```
-Nr /home/jeremie/Documents/drive_TNA/droid/samples/archive-parents/ -Ns /home/jeremie/.droid6.5/signature_files/DROID_SignatureFile_V96.xml -At ISO TAR
```
expected output:
```
/home/jeremie/Documents/drive_TNA/droid/samples/archive-parents/archive-parent.iso,fmt/468
iso://home/jeremie/Documents/drive_TNA/droid/samples/archive-parents/archive-parent.iso!/custom …
```

fix: iso prefix in CLI when expanding ISO archives

---

droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/DroidMainFrame.form
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/DroidMainFrame.java

fix filter button that was trimmed ("..." instead of "On") on windows on java 8 following https://github.com/digital-preservation/droid/pull/431
[Becoming complicated to maintain 2 versions (java 11 & 8), 3 OS (Mac Ubuntu Windows) and 2 bundles (with and without jre)...]

Fix filter button on windows on java8

---

.gitignore
.travis.yml
README.md
droid-parent/pom.xml
droid-results/pom.xml

This adds JaCoCo code coverage to the build.
As an example of use, when running `mvn site` you will now get a `jacoco/index.html` file inside the `target/site` folder of each module (e.g. `droid-core`). This shows comprehensive code coverage of tests.
In addition this adds support for coveralls.io which allows you to easily view the Code Coverage and changes through time in a nice web GUI. See: https://coveralls.io/github/digital-preservation/droid

Add Code Coverage to the build

---

droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/DroidCommandLine.java
droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/DroidCommandLineTest.java
droid-container/src/main/java/uk/gov/nationalarchives/droid/container/ole2/Ole2IdentifierEngine.java

so separated out the 2 error handling by whether we use file or InputStream.
This will make sure that we do not arbitrarily suggest increasing the memory. My analysis of the code indicated that the error message was introduced many years back when we used only `InputStream` this constructor's documentation indicated that it is more memory intensive and there are suggestions to use the constructor which takes in a `File`
We subsequently introduced that constructor (which uses nio) but the memory error message was kept in as it is. This PR separates the two. 
Helps with one part of https://github.com/digital-preservation/droid/issues/439

nio File based POIFS is optimized for memory, 

---

droid-export/src/main/java/uk/gov/nationalarchives/droid/export/CsvItemWriter.java
droid-export/src/test/java/uk/gov/nationalarchives/droid/export/CsvItemWriterTest.java

Fix #440 
this is new in 6.5.
This is due to a change in the library used to create CSV format (done by @adamretter to improve processing speed).
The library by default outputs files in a different format according to the operating system (using the operating system's own convention), while the previous one just used Unix format.
```
https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/common/Format.java
*  <li><b>lineSeparator:</b> the 1-2 character sequence that indicates the end of a line. Newline sequences are different across operating systems. Typically:
*		<ul>
*			<li>Windows uses carriage return and line feed: <i>\r\n</i></li>
*			<li>Linux/Unix uses line feed only: <i>\n</i></li>
*			<li>MacOS uses carriage return only: <i>\r</i></li>
* …
```

fix: put back LF (unix) line separators in csv exports

---

droid-binary/bin/ChangeLog
droid-binary/pom.xml
droid-build-tools/pom.xml
droid-command-line/pom.xml
droid-container/pom.xml
droid-core-interfaces/pom.xml
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/IdentificationRequest.java
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/hash/SHA1HashGenerator.java
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/hash/SHA256HashGenerator.java
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/resource/BZipIdentificationRequest.java
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/resource/GZipIdentificationRequest.java
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/resource/TarEntryIdentificationRequest.java
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/resource/WebArchiveEntryIdentificationRequest.java
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/resource/ZipEntryIdentificationRequest.java
droid-core/pom.xml
droid-core/src/main/java/uk/gov/nationalarchives/droid/core/signature/compiler/ByteSequenceCompiler.java
droid-core/src/main/java/uk/gov/nationalarchives/droid/core/signature/droid6/SubSequence.java
droid-export-interfaces/pom.xml
droid-export/pom.xml
droid-help/pom.xml
droid-parent/pom.xml
droid-report-interfaces/pom.xml
droid-report/pom.xml
droid-results/pom.xml
droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/datasource/DerbyPooledDataSource.java
droid-swing-ui/pom.xml
droid-swing-ui/src/main/java/org/netbeans/swing/outline/TreePathSupport.java
droid-tools/pom.xml
pom.xml

fixed a series of issues preventing the preparation of the release of the project
- binaries changelog out of date
- documentation issues appearing only during release or when running `mvn javadoc:javadoc`, related to incorrect documentation (invalid tags, missing documentation, incorrect configuration when building on jdk 11 while jdk 8 is default)
- missing dependency

Prep release 6.5

---

droid-binary/bin/droid.sh

This change makes the .sh file work on Mac OSX Catalina and (though untested) should still work on other unix based distributions.

Update to shebang line

---

droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/CommandFactoryImpl.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/CommandLineParam.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/ProfileRunCommand.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/i18n/I18N.java
droid-command-line/src/main/resources/options.properties
droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/action/ProfileRunCommandTest.java
droid-help/src/main/resources/Web pages/Command line control.html
droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/ProfileContextLocator.java
droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/ProfileManager.java
droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/ProfileManagerImpl.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/profile/ProfileManagerImplTest.java

Allows global default profile properties to be overridden when creating a new profile.  This allows us to set profile properties directly on the command line, or by specifying an alternate profile property override file to use, or both.
**Usage**
To override a default profile property such as max bytes to scan, you specify it with the **-Pr** option:
`droid -a "/home/user/Documents" -R -p "/home/user/docprofile.droid" -Pr "profile.maxBytesToScan=1024"`
You can set more than one property by just specifying each as additional arguments:
`droid -a "/home/user/Documents" -R -p "/home/user/docprofile.droid" -Pr "profile.maxBytesToScan=1024" "profile.processZip=false"`
If you have a lot of properties you want to override all the time, or different sets of properties you want to re-use, you can …

Profile properties

---

droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/ListReportsCommand.java
droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/action/ListReportsCommandTest.java
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/archive/TrueZipArchiveHandler.java

2 Changes in here for 2 small bugfixes 
1) #482 - The StringBuilder was not being reinitialised, hence with every report iteration it added more and more details and printed it all
2) #505 - DPP files have a trailing null character in the names, trimming that would help get away from the error.

Bug fixes to remove duplicated lines and trim null character from zipEntry

---

droid-help/src/main/resources/Web pages/Third-party components.html
droid-report/pom.xml
droid-report/src/main/java/uk/gov/nationalarchives/droid/report/ReportTransformerImpl.java

Updated to use Open HTML TO PDF and removed itextpdf due to vulnerability (CVE-2021-43113)

Updated to use Open HTML TO PDF and removed itextpdf

---

droid-help/src/main/resources/Web pages/Third-party components.html
droid-report/pom.xml
droid-report/src/main/java/uk/gov/nationalarchives/droid/report/ReportTransformerImpl.java

vulnerability (CVE-2021-43113) (#675)

Updated to use Open HTML TO PDF and removed itextpdf due to

---

droid-binary/pom.xml
droid-build-tools/pom.xml
droid-command-line/pom.xml
droid-container/pom.xml
droid-core-interfaces/pom.xml
droid-core/pom.xml
droid-export-interfaces/pom.xml
droid-export/pom.xml
droid-help/pom.xml
droid-parent/pom.xml
droid-report-interfaces/pom.xml
droid-report/pom.xml
droid-results/pom.xml
droid-swing-ui/pom.xml
droid-tools/pom.xml
pom.xml

Switch to using Semantic Versioning - https://semver.org/
The vast majority of Java projects follow the Semantic Versioning Scheme these days

Switch to SemVer 2.0.0 versioning scheme

---

dependency-check/suppressions.xml
droid-binary/dependency-check/suppressions.xml
droid-build-tools/dependency-check/suppressions.xml
droid-command-line/dependency-check/suppressions.xml
droid-container/dependency-check/suppressions.xml
droid-core-interfaces/dependency-check/suppressions.xml
droid-core/dependency-check/suppressions.xml
droid-export-interfaces/dependency-check/suppressions.xml
droid-export/dependency-check/suppressions.xml
droid-help/dependency-check/suppressions.xml
droid-parent/dependency-check/suppressions.xml
droid-parent/pom.xml
droid-report-interfaces/dependency-check/suppressions.xml
droid-report/dependency-check/suppressions.xml
droid-results/dependency-check/suppressions.xml
droid-swing-ui/dependency-check/suppressions.xml
droid-tools/dependency-check/suppressions.xml
pom.xml

Introduced suppressions for the vulnerabilities related to spring to get the build succeeding again.
The droid build started failing on the spring framework vulnerability 
spring-core-5.3.20.jar: CVE-2016-1000027
spring-tx-5.3.20.jar: CVE-2016-1000027
Basically, this vulnerability has been identified long time back. A recent change in the nist database meant the database now sees v5.3.20 as vulnerable. 
https://nvd.nist.gov/vuln/detail/CVE-2016-1000027#VulnChangeHistorySection
See interesting details about the vulnerability here: https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#remoting-httpinvoker
As a result, I have introduced suppressions of checking for this particular entry until 1st October to get a successful build.

Introduced suppressions for the vulnerabilities related to spring

---

droid-core/src/main/java/uk/gov/nationalarchives/droid/core/signature/compiler/ByteSequenceCompiler.java
droid-core/src/main/java/uk/gov/nationalarchives/droid/core/signature/compiler/ByteSequenceSerializer.java
droid-core/src/test/java/uk/gov/nationalarchives/droid/core/signature/compiler/ByteSequenceCompilerTest.java
droid-core/src/test/java/uk/gov/nationalarchives/droid/core/signature/compiler/ByteSequenceSerializerTest.java
droid-tools/src/main/java/uk/gov/nationalarchives/droid/tools/SigTool.java
droid-tools/src/main/java/uk/gov/nationalarchives/droid/tools/SigUtils.java

?? symbols were being incorrectly included as part of the XML signature text.  They should instead be modelled as min/max offsets between what precedes them and what follows them.  This fix removes the ANY (??) matcher as a valid part of an anchoring sequence, as that was incorrect.
The fix is to ensure that the ANY type is not processed as part of the anchor text, and cannot be included in fragment text either.  Finally, sigtool correctly takes account of the anchor type (BOF/EOF) when serializing signatures.
sigtool will now correctly process `-b -p "04??[01:0C][01:1F]{28}([41:5A]|[61:7A]){10}(43|44|46|4C|4E)"`, with the ?? turned into min/max offset of 1.

FIXES: Any ?? matcher should not be part of sequences.

---

droid-binary/bin/droid.bat

Enclosed the launch path in double quotes so that the batch file can launch even if the path has a space in it

cater for possible blank space in launch path of droid on Windows

---

droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/CsvItemWriter.java

Fix for issue 900.
As we were copying reference of the HEADER, then subsequently modifying the HEADER to include a prefix based on algorithm, on the second run, it was complaining about a header mismatch between data and headers. Making a deep copy of the HEADERS solves the column name mismatch

issue-900 fix for hash column missing from the export

---

droid-binary/pom.xml
droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/CsvItemWriter.java
droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/ProfileResourceNode.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/profile/CsvItemWriterTest.java
droid-swing-ui/src/main/resources/uk/gov/nationalarchives/droid/gui/config/Bundle.properties

This PR has 3 fixes 
1) The slashes on windows in the no profile output were forward slashes, it is now changed to backslashes as consistent with 6.5.2
2) Bundled JRE is updated to the newer minor version.
3) A small issue related to terminology used on the preferences dialog is fixed to make the two options clearer

issue-898 path separator slashes to work as per OS

---

droid-binary/bin/sigtool.bat

Just included the embedded JRE path for sigtool as well.

Changes to use embedded JRE for the Windows batch file

---

droid-command-line/src/main/resources/archive-puids.properties
droid-core-interfaces/src/main/resources/archive-puids.properties
droid-results/src/main/resources/archive-puids.properties

A small PR to add PUIDs with ISO extension,that were newly added in v108, to the archives map.

Added new puids corresponding to iso in the archives map

---

droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/CommandFactoryImpl.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/CommandLineParam.java
droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/action/CommandFactoryTest.java

The actual changes related to the ticket is 2 folds 
1) In `CommandLineParam`, the `ARCHIVE_TYPES` and `WEB_ARCHIVE_TYPES` have been changed to make their arguments optional
2)  In `CommandFactoryImpl` if there are no arguments passed to -At or -Wt, the property override is defensive against null
There are tests added for command line without the arguments.
All other changes are code cleanup identified as warnings.

Made the arguments to -At and -Wt as optional

---

droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/CsvItemWriter.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/profile/CsvItemWriterTest.java

When we implemented additional headers for exporting one row per file, we had used the suffix beginning with 2 so the columns would be 
```
PUID, MIME_TYPE, PUID2, MIME_TYPE2, PUID3, MIME_TYPE3
```
it is now changed to be 
```
PUID, MIME_TYPE, PUID1, MIME_TYPE1, PUID2, MIME_TYPE2
```

bugfix: suffix for additional format headers to start with 1

---

droid-api/src/main/java/uk/gov/nationalarchives/droid/internal/api/DroidAPI.java
droid-api/src/test/java/uk/gov/nationalarchives/droid/internal/api/DroidAPITest.java
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/DroidCore.java
droid-core/src/main/java/uk/gov/nationalarchives/droid/core/BinarySignatureIdentifier.java

- Added a method on DroidCore
- In the API, if the identification method is "container", then get the format name based on puid from the signature
- Use that format name in the API result

Issue 1011 format name difference between api and UI

---

droid-container/pom.xml
droid-container/src/main/java/uk/gov/nationalarchives/droid/container/httpservice/ContainerSignatureHttpService.java
droid-container/src/main/java/uk/gov/nationalarchives/droid/container/httpservice/DateParseException.java

The container signature files are updated by using a simple "REST api" 
We used httpClient from apache common which has medium vulnerability and also it has been superseeded by another incarnation
This PR updates to use the latest version.

Migrated the signature file download client from obsolete version to current

---

droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/DroidMainFrame.java
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/config/ConfigDialog.java

A few Ux bugs (some long standing, some recent) are fixed 
1) Cancelling the "Preferences" dialog was not resetting the changes on the dialog - this might have been a long standing source of confusion for many people around the issue of "hash not generated" 
2) Whether to launch a new profile or not is decided by a few properties, there should have been signature files in that list, instead there was signature file URL
3) Cancelling the "Do you want to create a new profile?" question and then cancelling the preferences dialog was still setting the response code to be OK causing another issue in a specific situation (might have been masked by 1 above)

UI minor bugs

---

droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/export/ExportDialog.form
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/export/ExportDialog.java
droid-swing-ui/src/main/resources/uk/gov/nationalarchives/droid/gui/export/Bundle.properties

1) Export dialog was too big for its contents 
2) The tooltip is wrapped into 2 lines so it is much more readable.

Export dialog minimum size reduced and tooltip made multiline

---

droid-export/src/main/java/uk/gov/nationalarchives/droid/export/template/ExportTemplateBuilder.java
droid-export/src/test/java/uk/gov/nationalarchives/droid/export/template/ExportTemplateBuilderTest.java
droid-help/src/main/resources/Web pages/Exporting profiles.html
droid-parent/pom.xml

Merging the error message improvements into the release branch
The main change is, 
Earlier the order of checks was 
1) Is it a profile results column?
2) Is it a constant string column?
3) Anything else - treat it as Data modifier column 
Now we have changed the checking order between 2 and 3, this means "anything else" is treated as a constant string column and automatically, the associated error messages indicate syntax error accordingly

Improved the validation error messages on export template parsing

---

README.md
droid-binary/bin/droid.bat
droid-binary/bin/droid.sh
droid-binary/pom.xml
droid-help/src/main/resources/Web pages/FAQ.html
droid-help/src/main/resources/Web pages/Startup configuration.html

1) Updated the Readme and configuration section to say "upto Java 17"
2) Bundled latest JRE
3) Increased the default max memory to 1024MB in startup scripts

Updated to latest JRE, increased max memory and updated docs to reflect the changes

---

.github/workflows/ci.yml
droid-binary/dependency-check/suppressions.xml
droid-binary/pom.xml
droid-command-line/dependency-check/suppressions.xml
droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/DroidCommandLineTest.java
droid-export/dependency-check/suppressions.xml
droid-export/src/test/resources/jpa-test.properties
droid-parent/pom.xml
droid-report-interfaces/dependency-check/suppressions.xml
droid-report/dependency-check/suppressions.xml
droid-report/src/test/resources/jpa-test.properties
droid-results/dependency-check/suppressions.xml
droid-results/src/main/resources/jpa.properties
droid-results/src/test/java/uk/gov/nationalarchives/droid/profile/ProfileManagerImplTest.java
droid-results/src/test/resources/jpa-test.properties
droid-swing-ui/dependency-check/suppressions.xml
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/filechooser/ProfileFileChooser.java

This is now the latest version of derby.
This version needs Java 21. I've updated the bundled version to use 21.
The name of the driver class has changed and has been updated in all of
the places it's set.
I wanted to get this working on 21 anyway. DROID itself runs happily on
21 but the tests weren't passing because of how old Mockito was so I've
upgraded that.
I've removed versions 7 and 11 and 17 from the CI workflow.
I've updated the ci workflow to use an NVD API key which is set in the
repository secrets to stop the ci run taking an hour periodically.
I've removed the supressions for the old version of the derby DB
The last thing was an odd test failure in the tests for ProfileFileChooser
It was saying that multiSelectionEnabled was true when run on Java 21.
If you run DROID on Java …

DR2-2038 Upate Derby database

---

droid-parent/pom.xml
droid-results/pom.xml

For some reason, some of the recent dependency updates have broken this
and we're now getting Failed to load class of driverClassName org.apache.derby.iapi.jdbc.AutoloadedDriver in HikariConfig
This stops the error.

Explicitly add Derby dependency

---

droid-container/src/main/java/uk/gov/nationalarchives/droid/container/ContainerSignatureMatch.java
droid-container/src/main/java/uk/gov/nationalarchives/droid/container/FileMatcher.java
droid-container/src/main/java/uk/gov/nationalarchives/droid/container/ole2/Ole2IdentifierEngine.java
droid-container/src/main/java/uk/gov/nationalarchives/droid/container/zip/ZipIdentifierEngine.java
droid-container/src/test/java/uk/gov/nationalarchives/droid/container/ContainerMatchUtils.java
droid-container/src/test/java/uk/gov/nationalarchives/droid/container/ContainerSignatureMatchTest.java
droid-container/src/test/java/uk/gov/nationalarchives/droid/container/zip/ZipFailureFallbackTest.java
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/DroidMainFrame.java
droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/filechooser/ResourceSelectorDialog.java

This is trying to solve the issue here https://github.com/digital-preservation/pronom/issues/10
There are two changes.
One is to do glob matching on container file names. In both the
Ole2IdentifierEngine and the ZipIdentifierEngine, we at first try to get
the name from the container as is. If that doesn't work we do:
* Check if the string `{containerFileName}` is in the path. If it is,replace the placeholder with the container file name and match on that.
* Check if the path in the container file matches and files in the container using glob matching.
This is experimental and subject to change but as it shouldn't break any
existing functionality, I think this can go into main.

Add glob matching and container file name matching.

---

droid-api/src/main/java/uk/gov/nationalarchives/droid/internal/api/DroidAPI.java
droid-api/src/test/java/uk/gov/nationalarchives/droid/internal/api/DroidAPITest.java
droid-api/src/test/java/uk/gov/nationalarchives/droid/internal/api/DroidAPITestUtils.java
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/resource/FileSystemIdentificationRequest.java
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/resource/HttpIdentificationRequest.java
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/resource/HttpWindowReader.java
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/resource/S3IdentificationRequest.java

TDR have the case where there files in S3 have no extension. This allows
you to provide an extension which DROID will use rather than deriving it
from the name.

Allow extension override.

---

droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/datawriter/FormattedDataWriter.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/profile/ItemWriterImplTest.java

Should fix #1130
If you import a profile with a file with a space at the end from an OS
which allows it into DROID on Windows, the export will fail.
The file url comes in with %20 at the end which fails when calling
Path.get on Windows because spaces are not allowed at the end.
This detects if there's %20 at the end and trims it if it is running on
Windows.
The export now works for this scenario although there may be other
issues we've not found yet.

Trim file path with spaces at the end for Windows.

---

droid-core-interfaces/pom.xml

for ssooidc, there was a hardcoded value, dependabot PR updated the variable and complained about incompatibility with this version number. Using the variable will ensure it updates to same version as well

changed to use param instead of hardcoded value 

---

droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/ItemWriterImpl.java
droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/datawriter/FormattedDataWriter.java
droid-results/src/test/java/uk/gov/nationalarchives/droid/profile/ItemWriterImplTest.java

Fixes #1318
The start and end array tokens for the json output are being written
when the FormattedDataWriter is being initialised. We're not checking to
see if the JSON output option is set. I've added a check on the open and
close methods which has stopped this.
The reason the tests didn't catch this is because the [] is written when
close() is called and this is only called after the assertions in the
tests. I've updated the tests to call close after each one and they're
passing now where they weren't before.

Stop writing JSON array to CSV output

---

cli-tests/test/cli-test.bats
droid-build-tools/src/main/resources/checkstyle-main.xml
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/CleanCommand.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/CommandFactory.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/CommandFactoryImpl.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/CommandLineParam.java
droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/i18n/I18N.java
droid-command-line/src/main/resources/options.properties
droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/action/CleanCommandTest.java
droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/action/CommandLineParamTest.java

This will clean the folders out of the ~/.droid6 directory.
This is often what is recommended when DROID misbehaves so having a
command to do this will be useful.
It will delete the following directories and files
container_sigs/
signature_files/
profiles/
profile_templates/
droid.properties
log4j2.properties
tmp/

Create 'clean' option for DROID.

---

.github/scripts/generate_develop_release.py
.github/scripts/generate_release.py
.github/scripts/settings.xml
.github/workflows/develop_release.yml
.github/workflows/release.yml
droid-api/pom.xml
droid-binary/bin/ChangeLog
droid-binary/pom.xml
droid-build-tools/pom.xml
droid-command-line/pom.xml
droid-container/pom.xml
droid-core-interfaces/pom.xml
droid-core/pom.xml
droid-core/src/test/java/uk/gov/nationalarchives/droid/core/ThreadPoolExecutorTest.java
droid-export-interfaces/pom.xml
droid-export/pom.xml
droid-help/pom.xml
droid-help/src/main/resources/Web pages/Whats New.html
droid-parent/pom.xml
droid-report-interfaces/pom.xml
droid-report/pom.xml
droid-results/pom.xml
droid-swing-ui/pom.xml
droid-tools/pom.xml
pom.xml

- **Release 6.9.0**
- **Only run gpg signing on release**
- **Profile wrangling**
- **Update branch name**

6.9.0 release latest

---

droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/resource/HttpWindowReader.java
droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/resource/S3WindowReader.java
droid-core-interfaces/src/test/java/uk/gov/nationalarchives/droid/core/interfaces/resource/HttpWindowReaderTest.java

There was a bug where DROID was returning fmt/189 for files which should
have returned fmt/1827.
The bytes that are returned from createWindow in the WindowReaders are
stored in a SoftReference inside SoftWindow. The idea being that if the
system starts to run out of memory, the byte arrays can be reclaimed by
the garbage collector.
If this happens, the byte array is null and getByteArray inside
SoftWindow calls reloadWindowBytes to repopulate the byte array.
This method was not implemented because I originally thought that it
wasn't used as it was never called when running the tests or during
manual testing. The reason it was never called is that my dev machine
has plenty of memory so the GC never had to reclaim anything.
When DROID was running in the lambda inside TDR, it only had 2Gb …

Implement reloadWindowBytes
