droid-binary/bin/ChangeLog, droid-binary/bin/droid.bat, droid-binary/bin/droid.sh
Updated droid.bat, droid.sh and ChangeLog so version is 6.2
=> Changed version to 6.2

droid-container/src/main/java/uk/gov/nationalarchives/droid/container/ContainerFile.java, droid-container/src/main/java/uk/gov/nationalarchives/droid/container/ContainerSignature.java, droid-results/src/main/java/uk/gov/nationalarchives/droid/submitter/SubmissionGateway.java
Fix race condition on getCompiledBinarySignatures().
=> Fix container multiple identification bug.

droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/util/DroidUrlFormat.java, droid-core-interfaces/src/test/java/uk/gov/nationalarchives/droid/core/interfaces/util/DroidUrlFormatTest.java, droid-export/src/main/java/uk/gov/nationalarchives/droid/export/CsvItemWriter.java
=> Uri endcoder

droid-build-tools/src/main/resources/checkstyle-main.xml, droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/DroidCommandLine.java, droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/context/GlobalContext.java, droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/context/SpringUiContext.java, droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/TestContexCleanup.java
Refactor code responsible to create & destroy Spring context. Related to #31
=> Context refactor

droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/export/JDBCSqlItemReader.java
=> Sort csv export by URI.

droid-build-tools/src/main/resources/checkstyle-main.xml, droid-command-line/pom.xml, droid-container/pom.xml, droid-core-interfaces/pom.xml, droid-export-interfaces/pom.xml, droid-parent/pom.xml, droid-report-interfaces/pom.xml, droid-report/pom.xml, droid-results/pom.xml
Removed Cobertura plugin. Added new version of checkstyle.
=> Upgrade maven plugins for DROID build process.

droid-command-line/src/main/resources/archive-puids.properties, droid-core-interfaces/src/main/resources/archive-puids.properties, droid-results/src/main/resources/archive-puids.properties
It's not supported by rar library.
=> Remove RAR 5.0 from content analysation.

droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/report/ExportReportAction.java
=> Fix bug #74

droid-container/src/test/java/uk/gov/nationalarchives/droid/container/odf/OdfIdentifierTest.java, droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/config/RuntimeConfig.java, droid-core-interfaces/src/test/java/uk/gov/nationalarchives/droid/core/interfaces/archive/ArcArchiveHandlerTest.java, droid-core-interfaces/src/test/java/uk/gov/nationalarchives/droid/core/interfaces/archive/BZipArchiveHandlerTest.java, droid-core-interfaces/src/test/java/uk/gov/nationalarchives/droid/core/interfaces/archive/GZipArchiveHandlerTest.java, droid-core-interfaces/src/test/java/uk/gov/nationalarchives/droid/core/interfaces/archive/SevenZArchiveHandlerTest.java, droid-core-interfaces/src/test/java/uk/gov/nationalarchives/droid/core/interfaces/archive/TarArchiveHandlerTest.java, droid-core-interfaces/src/test/java/uk/gov/nationalarchives/droid/core/interfaces/archive/WarcArchiveHandlerTest.java, droid-core-interfaces/src/test/java/uk/gov/nationalarchives/droid/core/interfaces/resource/FileSystemIdentificationRequestTest.java, droid-core-interfaces/src/test/java/uk/gov/nationalarchives/droid/core/interfaces/resource/GZipIdentificationRequestTest.java, droid-core-interfaces/src/test/java/uk/gov/nationalarchives/droid/core/interfaces/resource/TarEntryIdentificationRequestTest.java, droid-core-interfaces/src/test/java/uk/gov/nationalarchives/droid/core/interfaces/resource/ZipEntryIdentificationRequestTest.java, droid-core/src/main/java/uk/gov/nationalarchives/droid/core/BinarySignatureIdentifier.java, droid-core/src/main/java/uk/gov/nationalarchives/droid/core/SignatureFileParser.java, droid-export/src/test/java/uk/gov/nationalarchives/droid/export/CsvItemWriterTest.java, droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/JaxbProfileSpecDao.java, droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/ProfileContextLocator.java, droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/ProfileManagerImpl.java, droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/datasource/DerbyPooledDataSource.java, droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/datasource/DerbyPooledDataSourceFactory.java, droid-results/src/main/resources/META-INF/spring-jpa.xml
#167 Introduced some incompatibility issues on windows, this pull request fix problems with paths and also contains new code to create DB pool.
=> Fix bugs from #167

droid-binary/assembly.xml
=> Fix unix permission in zip file.

.travis.yml, droid-binary/bin/droid.bat, droid-binary/bin/droid.sh, droid-parent/pom.xml, droid-report/src/test/java/uk/gov/nationalarchives/droid/report/JaxbReportSpecDaoTest.java, droid-results/pom.xml, droid-results/src/main/java/uk/gov/nationalarchives/droid/profile/FilterImpl.java, droid-results/src/main/java/uk/gov/nationalarchives/droid/signature/PronomSignatureService.java, droid-results/src/test/java/uk/gov/nationalarchives/droid/planet/xml/dao/JpaPlanetsXMLDaoTest.java, droid-results/src/test/java/uk/gov/nationalarchives/droid/profile/JpaProfileDaoTest.java, droid-results/src/test/java/uk/gov/nationalarchives/droid/profile/JpaProfileFilterTest.java, droid-results/src/test/java/uk/gov/nationalarchives/droid/profile/ProfileResourceNodePersistenceTest.java, droid-results/src/test/java/uk/gov/nationalarchives/droid/report/dao/JpaReportDaoTest.java, droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/filechooser/ResourceSelectorDialog.java, droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/treemodel/ExpandingTreeListener.java, droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/worker/DroidJob.java
Fixed pull request from @adamretter 
- Drop Java 7 support, Java8 is minimum
- Add Java 9 support.
=> Java 8 and Java 9 updates for droid

droid-core/src/main/java/uk/gov/nationalarchives/droid/core/BinarySignatureIdentifier.java
Closes https://github.com/digital-preservation/droid/issues/199
=> Make getSigFile() public. #199

.travis.yml
https://www.oracle.com/technetwork/java/javase/eol-135779.html
=> End of support for oracle jdk 9 and 10

droid-help/src/main/resources/Web pages/Detecting duplicate files.html
Update link of National Software Reference Library _et alia_
=> Minor fixes

droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/archive/SevenZipArchiveHandler.java
In a similar way it's done in other containers
=> added lastmodified for files inside ziparchive

droid-swing-ui/checkstyle/suppressions.xml, droid-swing-ui/src/main/java/org/netbeans/swing/outline/TreePathSupport.java
PR to fix https://github.com/digital-preservation/droid/issues/306 based on PR https://github.com/apache/netbeans/pull/1639
related to netbeans bug: https://issues.apache.org/jira/browse/NETBEANS-3401
=> Fix folders messed up in UI

droid-binary/assembly.xml, droid-binary/pom.xml
Enable windows users to also use their own java JRE to run droid.
=> upd: binary bundle without jre now works for windows too

droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/filter/domain/PUIDMetadata.java
* It's incredibly horrible trying to find a PUID value amongst unsorted thousands in the Filter dialog.  
This just sorts the PUIDs initially when the dialog is built, to make it easy to find the PUIDs you want
to add.
=> ENHANCE: sort the PUID values in the filter dialog.

droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/report/ExportReportAction.java
* Path can be null, but was just doing lastSelectedDir.toFile().
* Just add null test and pass null if so , rather than trying to get tofile().
=> FIX: NullPointerException on Report / Export... button click.

.travis.yml
Get's the build passing again on Travis CI.
=> Fix Travis CI build for MacOS

droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/DroidMainFrame.java, droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/ProfileForm.java
Allows you to drag files and folders into a new profile rather than having to use the selection dialog.
Tested on Ubuntu 16.04 - needs testing on Windows and Mac.
Also see https://github.com/digital-preservation/droid/issues/204
=> ENHANCE: adds drag drop support for files into a profile GUI window,

droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/DroidMainFrame.form, droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/DroidMainFrame.java
fix display of filter checkbox on main screen
previously:
after fix:
=> fix: checkbox filter icon display on main screen

droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/NoProfileRunCommand.java
Fixed such that. 
When recursive, the filter created includes folders 
When non-recursive, the filter created does not use folders. 
[Update Jeremie] fix https://github.com/digital-preservation/droid/issues/410
=> Changed such that the DirStream filter ignores folders if non-recursive

README.md
Updates the URL for the Travis-CI build status badge.
=> Fix the Travis build status badge in README.md

README.md
Fix: https://github.com/digital-preservation/droid/issues/445
@adamretter by the code I've looked I think it's the only place that needs to be changed. And it seems that the project doesn't exist anymore on your account.
=> upd: appveyor account in README

droid-parent/pom.xml
=> Updated to use newer version of log4j as there was a vulnerability 

droid-binary/pom.xml
=> Update JRE to latest version from adoptium.net

droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/export/ExportDialog.form, droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/export/ExportDialog.java
=> Fix export encoding option

droid-binary/pom.xml
Updated the version for bundled JRE
=> updated bundled JRE version to the newest of Java11

.github/workflows/ci.yml, droid-api/pom.xml, droid-binary/pom.xml, droid-build-tools/pom.xml, droid-command-line/pom.xml, droid-container/pom.xml, droid-core-interfaces/pom.xml, droid-core/pom.xml, droid-export-interfaces/pom.xml, droid-export/pom.xml, droid-help/pom.xml, droid-parent/pom.xml, droid-report-interfaces/pom.xml, droid-report/pom.xml, droid-results/pom.xml, droid-swing-ui/pom.xml, droid-tools/pom.xml, pom.xml
Introduced artifact upload, so that the full build will be available in github to download
=> re introduced artifact upload with github action

droid-api/pom.xml, droid-binary/pom.xml, droid-build-tools/pom.xml, droid-command-line/pom.xml, droid-container/pom.xml, droid-core-interfaces/pom.xml, droid-core/pom.xml, droid-export-interfaces/pom.xml, droid-export/pom.xml, droid-help/pom.xml, droid-parent/pom.xml, droid-report-interfaces/pom.xml, droid-report/pom.xml, droid-results/pom.xml, droid-swing-ui/pom.xml, droid-tools/pom.xml, pom.xml
Updated the version numbers as we would like to call the next release 6.8.0
=> Updated the version number in line with potential release

dependency-check/suppressions.xml, droid-api/dependency-check/suppressions.xml, droid-binary/dependency-check/suppressions.xml, droid-build-tools/dependency-check/suppressions.xml, droid-command-line/dependency-check/suppressions.xml, droid-container/dependency-check/suppressions.xml, droid-core-interfaces/dependency-check/suppressions.xml, droid-core/dependency-check/suppressions.xml, droid-export-interfaces/dependency-check/suppressions.xml, droid-export/dependency-check/suppressions.xml, droid-help/dependency-check/suppressions.xml, droid-parent/dependency-check/suppressions.xml, droid-parent/pom.xml, droid-report-interfaces/dependency-check/suppressions.xml, droid-report/dependency-check/suppressions.xml, droid-results/dependency-check/suppressions.xml, droid-swing-ui/dependency-check/suppressions.xml, droid-tools/dependency-check/suppressions.xml
This is the latest version of spring. I've also removed the suppressions
files for the dependency CVE check as we don't need them any more.
=> Upgrade spring and remove suppressions.

droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/CommandFactory.java, droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/CommandFactoryImpl.java, droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/CommandLineParam.java, droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/action/CommandFactoryTest.java, droid-help/src/main/resources/Web pages/Command line control.html
They're not necessary and they're confusing.
=> Remove --HTTP and --S3 flags

droid-binary/bin/droid.sh
fixes: https://github.com/digital-preservation/droid/issues/1267
=> Add option for enableExtensionFunctions for Mac

README.md
- **Add line break**
- **Remove line break**
=> test branch 2

README.md
- **Add line break**
- **Remove line break**
- **Add line break again**
=> test branch 3

.gitignore, README.md
This is for the GitHub pages branch. I added branch protections to it to prevent people from pushing directly to the gh-pages` branch
=> GitHub Pages README update
